name: build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
        runner:
          - 'ubuntu-latest'
          - 'ubuntu-24.04-arm'
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: mvn -B install > >( tee out )
        continue-on-error: true
      - run: grep "^\[INFO\] Tests run:" out
        continue-on-error: true
      - run: tail -100 out
