# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: PostreSQL
      shell: bash
      run: |
        sc config postgresql-x64-13 start=auto
        net start postgresql-x64-13
        "$PGBIN/psql" -c "SELECT 1"
        "$PGBIN/psql" -c "ALTER ROLE postgres PASSWORD 'postgres'"
        exit 1
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean install -DskipTests --file pom.xml
