# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: pg config
      shell: bash
      run: cat "$PGDATA/postgresql.conf"
    - name: fail
      run: fail
    - name: Enable PostgreSQL service
      run: sc config postgresql-x64-13 start=auto
    - name: Start PostgreSQL
      run: net start postgresql-x64-13
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Test PostgreSQL
      shell: bash
      run: |
          echo "PGDATA=$PGDATA"
          echo "PGBIN=$PGBIN"
          echo "PGUSER=$PGUSER"
          "$PGBIN/psql" -c "SELECT 1"
          fail
    - name: Build with Maven
      run: mvn -B clean install -DskipTests --file pom.xml
