# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Start PostgreSQL
      run: sc config postgresql-x64-13 start=auto
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test PostgreSQL
      run:
      - echo "x y z"
      - echo "a\nb\nc"
      - dir env:
      - echo "PGDATA=$PGDATA"
      - echo "PGDATABASE=$PGDATABASE"
      - echo "PGPORT=$PGPORT"
      - echo "PGUSER=$PGUSER"
      - "C:\Program Files\PostgreSQL\13\bin\psql" -c "SELECT 1"
    - name: Build with Maven
      run: mvn -B clean install -DskipTests --file pom.xml
